#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "Boilerplate"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Anzal"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "337/215 Kazmain Road,Mansoor Nagar,Lucknow"
mobile = "+919140459232"
email = "cofclan145@.com"
# contact form action
contact_form_action = "https://formspree.io/f/xqkwrjvz" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
mainSections = ["blog"]
# about widget content
about_widget_content = "Some view technology as a great evil that slowly diminishes our humanity, while others view it as a way to bring the world closer together and to help solve some of our greatest challenges."
# footer content
footer_content = "**BE A GEEK NOT A CREEP.**"
# copyright
copyright = "Created by **Anzal Husain Abidi** Ⓒ "

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to Anzal's Blog"
image = "images/banner.jpg"
background_image = "/images/banner-bg-shape.svg"
content = "**A place for geeks to lurk upon some techy stuff and engage in  wholesome comment exchanges.**"
button_label = "Know About Me"
button_link = "about/"

# Advertise
[advertisement]
image = "images/promotion.jpg"
link = "https://poki.com/en/g/stickman-hook" 

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/anzal.abidi/"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/AnzalAbidi"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/anzalabidi/"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/anzal1"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/anzal-husain-abidi-740a40204/"