about_widget_content = "Some view technology as a great evil that slowly diminishes our humanity, while others view it as a way to bring the world closer together and to help solve some of our greatest challenges."
address = "337/215 Kazmain Road,Mansoor Nagar,Lucknow"
author = "Anzal"
contact_form_action = "https://formspree.io/f/xqkwrjvz"
copyright = "Created by **Anzal Husain Abidi** Ⓒ "
custom_script = ""
description = "A techy blog website for stuff i came across in my engineering tenure."
email = "cofclan145@gmail.com"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "**BE A GEEK NOT A CREEP.**"
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
<<<<<<< HEAD
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Anzal"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "337/215 Kazmain Road,Lucknow"
=======
logo_width = "150x"
mainSections = ["blog"]
>>>>>>> 4348bab78a654db0ef3d5b841653c23d1532f190
mobile = "+919140459232"
navbar_fixed = true
recent_post_title = "Recent Post"
<<<<<<< HEAD
mainSections = ["blog"]
# about widget content
about_widget_content = "Some view technology as a great evil that slowly diminishes our humanity, while others view it as a way to bring the world closer together and to help solve some of our greatest challenges."
# footer content
footer_content = ">**BE A GEEK NOT A CREEP.**"
# copyright
copyright = "Created by **Anzal Husain Abidi** Ⓒ "

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
=======
search = true
[advertisement]
image = "images/promotion.jpg"
link = "https://poki.com/en/g/stickman-hook"
>>>>>>> 4348bab78a654db0ef3d5b841653c23d1532f190
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "**A place for geeks to lurk upon some techy stuff and engage in  wholesome comment exchanges.**"
enable = true
image = "images/banner.jpg"
title_large = "Welcome **!**"
title_small = "to Anzal's Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/anzal.abidi/"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/AnzalAbidi"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/anzalabidi/"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "https://github.com/anzal1"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/anzal-husain-abidi-740a40204/"
title = "linkedin"
